POST http://localhost:5000/users/adduser
Content-Type: application/json

{
    "name":"fe",
    "surname":"al",
    "email":"fevzi31@gmail.com",
    "password":"123123"
}

###

GET http://localhost:5000/users/getallusers
Content-Type: application/json

{
    "name":"fevzi",
    "surname":"ata",
    "email":"fevzi1@gmail.com",
    "password":"123123"
}

###

POST  http://localhost:5000/students/addstudent
Content-Type: application/json

{
    "name":"Fevzi",
    "surname":"Yeter",
    "courses":[]
}

###

DELETE  http://localhost:5000/students/deletestudent
Content-Type: application/json

{
  "_id":"6378f3bf40366f73bfd459e8"
}

###

POST  http://localhost:5000/courses/addstudent
Content-Type: application/json

{
  "studentId":"637b3212176ea113e8f6aa3e",
  "courseName":"Piyano"
}

###

POST  http://localhost:5000/courses/addcourse
Content-Type: application/json

{
  "name" : "Gitar"
}


###

POST  http://localhost:5000/courses/deletestudent
Content-Type: application/json

{
  "studentId":"637b3212176ea113e8f6aa3e",
  "courseName" : "Piyano"
}

###

POST http://localhost:5000/bill/addbill
Content-Type: application/json

{
    "date":"10/10/2020",
    "class":"al",
    "isPaid":false,
    "localDate":"123123",
    "studentID":"15616546546511"
}

###